1. What does Pandas stand for?

- Panel data or Python data analysis.

2. What are the 2 collections used in Pandas?

- Series and Dataframes.

3. Name 4 things Pandas can do for us.
 - load
 - manipulate
 - prepare
 - model

4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?

   - inplace

5. What is a CSV?
  - Comma Separated Value

6. When cleaning data what values do we not like in our data?
  - We don't like NULL values.

In [2]:
#Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

arr = np.arange(12)

arr_reshaped = arr.reshape(2, 3, 2)

print(arr_reshaped)


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [3]:
#Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

import numpy as np

arr = np.linspace(0, 20, 6)

print(arr)


[ 0.  4.  8. 12. 16. 20.]


In [9]:
# Make a Deep Copy of the above array

original_arr = np.linspace(0, 20, 6)

deep_copy_arr = original_arr.copy()

print(deep_copy_arr)

[ 0.  4.  8. 12. 16. 20.]


In [15]:
#Concatenate these 3 arrays into a new array named 'newArray'...

       # ([[25, 16]])
       # ([[11, 2], [13, 4]])
       # ([[7, 81], [5, 6], [11, 12]])

import numpy as np

array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array1, array2, array3), axis=0)
print(newArray)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [16]:
#Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray, axis=0)
print(sortedArray)


[[ 5  2]
 [ 7  4]
 [11  6]
 [11 12]
 [13 16]
 [25 81]]


In [4]:
#Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

var1, var2, var3, var4 = reshapedArray
print(var1)
print(var2)
print(var3)
print(var4)


<class 'NameError'>: name 'reshapedArray' is not defined

In [5]:
#Combined and sort the following arrays into one called 'comboArray' ...

    #one = ([10, 11, 12, 13, 14, 15, 16, 17])
    #two = ([20, 21, 22, 23, 24, 25, 26, 27])
    #three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three), axis = 0)
print(comboArray)

comboArray = np.sort(comboArray)
print(comboArray)

[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [6]:
#Take 'comboArray' and perform the following slicing activities:

print(comboArray[2])

print(comboArray[3:])

print(comboArray[4:15])

print(comboArray[-6:24])

print(comboArray[:-10])

print(comboArray[16:27:2])

print(comboArray[::-5])

2
[ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [12]:
#Using Series, create a DataFrame that looks like this:

import numpy as np
import pandas as pd

ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name= 'Ingredients')
quantity = pd.Series([4, 1, 2, 1], name= 'Quantity')
unit = pd.Series(['cups', 'cup', 'large', 'can'], name= 'unit')

brunch = pd.concat([ingredients, quantity, unit], axis=1)
print(brunch)

  Ingredients  Quantity   unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [ ]:
#Take this data and create a DataFrame named studentData

import pandas as pd

data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)
print(studentData)

In [17]:
#Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

 #Create DataFrame
studentData = pd.DataFrame(data)

# New column with desserts
studentData['Deserts'] = ["ice cream", "Cashew Fudge", "waffles", "Carrot Halwa"]

print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffles  
3  Carrot Halwa  


In [ ]:
#Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by= ['Name', 'address'], inplace=True)
studentData

In [ ]:
#Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')
df =pd.read_csv("cows_and_goats.csv")
df 

In [ ]:
#Using Pandas, make your own .CSV file with data on vegetables and save it. Using Pandas, make a change to your CSV file, and save a copy with a different name
import pandas as pd

veggies = pd.DataFrame({'corn': [35, 536], 'radishes': [23, 310]}, index=['small farm', 'big farm'])
veggies.to_csv('veggies.csv')

veggies = pd.read_csv('veggies.csv')
print(veggies)